# serverless.yml
component: nextjs # (必填) 组件名称，此处为nextjs
name: NextTS # (必填) 实例名称
org: betterlin # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid
app: NextTSDemo # (可选) 该 next.js 应用名称
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src: ./
  functionName: NextTSDemo
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release